### ISSUE TITLE
[UI] 대화보관목록,대화,피드백 화면 작성

### ISSUE THREAD

**Issue by algochemy** [crosswaves/cross_wave#2]
### 파일구조

📦lib
 ┣ 📂data
 ┃ ┗ 📂domain
 ┃ ┃ ┗ 📂model
 ┃ ┃ ┃ ┗ 📜conversation.dart
 ┣ 📂presentation
 ┃ ┣ 📂components
 ┃ ┃ ┣ 📜conversation_card.dart
 ┃ ┃ ┣ 📜conversation_list.dart
 ┃ ┃ ┗ 📜feedback_popup.dart
 ┃ ┣ 📜archive_screen.dart
 ┃ ┣ 📜conversation_screen.dart
 ┃ ┗ 📜feedback_screen.dart
 ┗ 📜main.dart

---

### 파일 설명

📜main.dart : 프로그램 실행

📜conversation.dart : 대화 모델 클래스

📜archive_screen.dart : 이전 대화 목록 화면
📜conversation_list.dart : 단일 대화 화면
📜feedback_screen.dart : 단일 대화에 대한 피드백 화면

📜conversation_card.dart : 단일 대화 화면에 사용되는 Card 위젯
📜conversation_list.dart: 이전 대화 목록을 표시하고 단일 대화 화면에 접근하기 위한 GestureDetector 위젯
📜feedback_screen.dart : 피드백 팝업메시지에 사용되는 AlertDialog 위젯

**Comment by kaggle68** [comment]
저는 시간이 조금 더 걸릴 듯 합니다 ;;

**Comment by david-s-kim** [comment]
좋습니다 👍👍
